

#MAIN PAGE
MAIN_TITLE_TEXT = "Azure OpenAI Assistants"
MAIN_ASSISTANT_SELECT_TEXT = "Select Your Assistant"
MAIN_NO_ASSISTANT_TEXT = "No Assistants created. Create your first Assistant"
MAIN_ASSISTANT_CHAT_WELCOME = "How can I help you?"
MAIN_ASSISTANT_UPLOAD_DOCUMENT = "Upload a document"

MAIN_FILE_UPLOAD_OK = "File uploaded to OpenAI successfully!"
MAIN_FILE_UPLOAD_KO = "File upload failed!"

#ASSISTANT MANAGEMENT PAGE
MANAGE_TITLE_TEXT = "Manage your Azure OpenAI Assistants"
MANAGE_ASSISTANT_SELECT_TEXT = "Select Your Assistant"
MANAGE_SELECTED_ASSISTANT_ID = "Assistant Id"
MANAGE_SELECTED_ASSISTANT_INSTRUCTIONS = "Assistant Instructions"
MANAGE_SELECTED_ASSISTANT_CAPABILITIES = "Capabilities"
MANAGE_SELECTED_ASSISTANT_CAPABILITIES_CODE_INTERPRETER = "Code Interpreter"
MANAGE_SELECTED_ASSISTANT_TOOLS = "Assistant tools"
MANAGE_SELECTED_ASSISTANT_FUNCTIONS = "Functions"
MANAGE_SELECTED_ASSISTANT_FILES = "Files"

#VARIABLE CONFIGURATION PAGE
VARIABLE_CONFIG_PAGE_OPENAI_ENDPOINT_FIELD   = "Azure OpenAI Service Endpoint (https://YOUR_AOAI_RESOURCE_NAME.openai.azure.com/)"
VARIABLE_CONFIG_PAGE_OPENAI_KEY_FIELD        = "Azure OpenAI Service Key"
VARIABLE_CONFIG_PAGE_OPENAI_DEPLOYMENT_FIELD = "Azure OpenAI Deployment Name"